### ISSUE TITLE
method textDocument/codeAction is not supported by any of the servers registered for the current buffer

### ISSUE THREAD

**Issue by Jake-kim-sang-hyun** [arch-spatula/neovim-setup#39]
https://github.com/neovim/neovim/issues/13508

**Comment by arch-spatula** [comment]
https://github.com/vuejs/language-tools/issues/3925

**Comment by arch-spatula** [comment]
https://github.com/neovim/nvim-lspconfig/blob/master/doc/server_configurations.md#volar

**Comment by arch-spatula** [comment]
https://www.reddit.com/r/neovim/comments/1b7f28d/volar_200/

**Comment by arch-spatula** [comment]
https://github.com/vuejs/language-tools

여기가 vue LSP 레포

https://github.com/vuejs/language-tools/tree/master/packages/language-server

https://github.com/vuejs/language-tools/tree/master/packages/language-server

위 2개 링크 참고하기

**Comment by arch-spatula** [comment]
![image](https://github.com/arch-spatula/neovim-setup/assets/84452145/744cc37e-0cf4-40c9-8671-c5e204fee796)

**Comment by arch-spatula** [comment]
```sh
npm install -g @vue/typescript-plugin
```

**Comment by arch-spatula** [comment]
npm 글로벌 설치 경로 파악이 필요함

https://github.com/vuejs/language-tools/issues/3925#issuecomment-1987051939

위 설정이 결국 먹힘

**Comment by arch-spatula** [comment]
```lua
			-- JS & TS
			lspconfig.tsserver.setup({
				init_options = {
					plugins = {
						{
							name = "@vue/typescript-plugin",
							location = "/global/npm/pakage/dir/lib/@vue/language-server",
							languages = {
								"javascript",
								"typescript",
								"vue",
							},
						},
					},
				},
				filetypes = {
					"javascript",
					"typescript",
					"vue",
				},
				capabilities = capabilities,
			})
```

**Comment by arch-spatula** [comment]
https://github.com/yaegassy/coc-volar

vue 호환성을 확인하기 바랍니다.

**Comment by arch-spatula** [comment]
```
:MasonInstall vue-language-server@1.8.27
```

위 커맨드로 해결하는 것도 현재 전략 중 하나라고 봅니다.
