### ISSUE TITLE
alpha-0.1.0 버전

### ISSUE THREAD

**Issue by arch-spatula** [arch-spatula/neovim-setup#6]
```
alpha-0.1.0
```

- [x] #5 
- [x] #16
- [x] #11
- [x] #17
- [x] #13
- [x] #24

**Comment by Jake-kim-sang-hyun** [comment]
window 환경에서 설치 nvchad 확인하고 문서 추가해주세요

**Comment by Jake-kim-sang-hyun** [comment]
키맵과 관련된 전체 문서도 한번 정리해주세요

**Comment by Jake-kim-sang-hyun** [comment]
nvim telescope windows에서는 어디서 실행해도 루트부터 검색을 시작합니다. 파일을 연 시점이 아닙니다.
